### ISSUE TITLE
Django 1.5 support

### ISSUE THREAD

**Issue by yunmanger1** [disqus/django-mailviews#7]
`direct_to_template`, which is used in [previews](/disqus/django-mailviews/blob/master/mailviews/previews.py#L86), is not available in Django 1.5; use `django.views.generic.TemplateView` instead

**Comment by tkaemming** [comment]
The README has been updated with all supported versions (up to Django 1.8, and Python 3): https://github.com/disqus/django-mailviews#testing-and-development
